"use strict"
const assert = require("assert")
const cp = require("child_process")
const fs = require("fs")
const os = require("os")
const path = require("path")
const skill = path.resolve(__dirname, "..")
const build = path.resolve(skill, "../build-signal-graph")
const temp = fs.mkdtempSync(path.join(os.tmpdir(), "signal-render-test-"))
const run = (command, args, cwd = skill) => { const result = cp.spawnSync(command, args, { cwd, encoding: "utf8", shell: process.platform === "win32" }); if (result.status !== 0) throw new Error(`${command} ${args.join(" ")} failed\n${result.stdout}\n${result.stderr}`) }
try {
  run("tsc", ["-p", path.join(build, "tests/tsconfig.json")])
  run("tsc", ["--strict", "--target", "ES2022", "--module", "commonjs", "--outDir", path.join(temp, "model"), path.join(build, "assets/signal.ts"), path.join(build, "assets/architecture.ts"), path.join(build, "tests/runtime.ts")])
  run("node", [path.join(temp, "model/tests/runtime.js")])
  run("tsc", ["--strict", "--target", "ES2022", "--module", "commonjs", "--outDir", path.join(temp, "renderer"), path.join(skill, "scripts/render.ts")])
  const { renderArchitecture } = require(path.join(temp, "renderer/render.js"))
  const model = require(path.join(temp, "model/assets/architecture.js")).default
  const htmlA = renderArchitecture(model), htmlB = renderArchitecture(model)
  assert.strictEqual(htmlA, htmlB, "rendering must be deterministic")
  assert(htmlA.includes("Architecture interaction map") && htmlA.includes("end-to-end paths"))
  assert(htmlA.includes("data-edge=") && htmlA.includes("data-paths=") && htmlA.includes("data-node="))
  assert(htmlA.includes("POST /orders") && htmlA.includes("GET cached order") && htmlA.includes("INSERT order") && htmlA.includes("publish order.created"))
  assert(htmlA.includes("marker-end:url(#arrow)") && htmlA.includes("selectPath"), "direction and path selection are required")
  assert.strictEqual((htmlA.match(/data-node="OrdersApi"/g) || []).length, 1, "one component identity must produce one box")
  assert(!htmlA.includes("class=\"card declaration\""), "renderer must not fall back to a declaration-card inventory")
  assert(htmlA.includes("default-src 'none'"))

  const hostile = `<img src=x onerror="alert(1)">&'`
  const actor = Object.freeze({ kind: "actor", name: hostile })
  const system = Object.freeze({ kind: "system", name: "System" })
  const service = Object.freeze({ kind: "service", name: "API", system })
  const schema = Object.freeze({ description: "string", shape: "primitive" })
  const endpoint = Object.freeze({ kind: "endpoint", name: hostile, owner: service, method: "POST", path: "/<x>", request: schema, response: schema })
  const step = Object.freeze({ action: "request", from: actor, to: endpoint, operation: `POST /<x> ${hostile}`, contract: endpoint })
  const flow = Object.freeze({ kind: "flow", name: "hostile", steps: Object.freeze([step]) })
  const hostileHtml = renderArchitecture({ Actor: actor, System: system, Api: service, Endpoint: endpoint, Flow: flow })
  assert(!hostileHtml.includes(hostile), "untrusted values must not appear raw")
  assert(hostileHtml.includes("&lt;img src=x onerror=&quot;alert(1)&quot;&gt;"))
  assert.throws(() => renderArchitecture({ Actor: actor, Alias: actor }), /Duplicate declaration object/)
  const missing = Object.freeze({ kind: "service", name: "Missing", system })
  const badEndpoint = Object.freeze({ ...endpoint, owner: missing })
  const badStep = Object.freeze({ ...step, to: badEndpoint, contract: badEndpoint })
  assert.throws(() => renderArchitecture({ Actor: actor, System: system, Endpoint: badEndpoint, Flow: Object.freeze({ kind: "flow", name: "bad", steps: [badStep] }) }), /outside the root architecture/)
  console.log("Signal DSL and interactive renderer tests passed")
} finally { fs.rmSync(temp, { recursive: true, force: true }) }
